// <auto-generated />
using System;
using ControlePonto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControlePonto.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlePonto.Models.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPF");

                    b.Property<string>("CargaHoraria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargaHoraria");

                    b.Property<string>("CargaHorariaSEmanal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargaHorariaSEmanal");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cargo");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complemento");

                    b.Property<string>("DiadaSemana")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiadaSemana");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Habilitacao")
                        .HasColumnType("bit")
                        .HasColumnName("Habilitacao");

                    b.Property<string>("HoraFim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoraFim");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoraInicio");

                    b.Property<string>("LinguaEstrangeira")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinguaEstrangeira");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numero");

                    b.Property<string>("SalarioProposto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SalarioProposto");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefone");

                    b.Property<int?>("TempodeDescanso")
                        .HasColumnType("int")
                        .HasColumnName("TempodeDescanso");

                    b.HasKey("id");

                    b.ToTable("TabFuncionario");
                });

            modelBuilder.Entity("ControlePonto.Models.HorarioModel", b =>
                {
                    b.Property<int>("HorarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HorarioID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CargaHoraria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargaHoraria");

                    b.Property<string>("CargaHorariaSEmanal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargaHorariaSEmanal");

                    b.Property<string>("DiadaSemana")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiadaSemana");

                    b.Property<int?>("Funcionarioid")
                        .HasColumnType("int");

                    b.Property<string>("HoraFim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoraFim");

                    b.Property<string>("HoraInicio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoraInicio");

                    b.Property<int?>("TempodeDescanso")
                        .HasColumnType("int")
                        .HasColumnName("TempodeDescanso");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("HorarioID");

                    b.HasIndex("Funcionarioid");

                    b.ToTable("TabHorario");
                });

            modelBuilder.Entity("ControlePonto.Models.HorarioModel", b =>
                {
                    b.HasOne("ControlePonto.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionarioid");

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
